version: 2.1
orbs:
  firebase-deploy: azdevs/firebase-deploy@1.0.0
  hugo: circleci/hugo@0.6.0
jobs:
  build:
    executor:
      name: hugo/cibuilds
    steps:
      - checkout
      - run:
          name: pull theme down
          command: |
            git submodule init
            git submodule update
      - hugo/install:
          version: 0.74.3
      - hugo/hugo-build
      - persist_to_workspace:
          root: ~/project
          paths:
            - public
            - resources
  deploy:
    docker:
      - image: 'circleci/node:lts'
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - firebase-deploy/deploy:
          token: $FIREBASE_TOKEN
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

