---
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/personal-site
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Site Build
          command: hugo --minify
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN
